---
name: "YouTube Auto Metadata"
guid: "bb165877-2d2a-458d-aa02-52b9f632d974"
version: "0.1.0.0"
targetAbi: "10.11.2"
framework: "net9.0"
overview: "Automatically fetch YouTube metadata by title."
description: >
  Jellyfin metadata plugin that fetches metadata and images from YouTube
  by title (no YouTube ID required in filename), with optional AI cleanup.
category: "Metadata"
owner: "TimLuist1"
artifacts:
  - "Jellyfin.Plugin.YoutubeMetadata.dll"
changelog: >
  Initial release with title-based matching, image import, and optional AI cleanup.
